services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: radio_lan_jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/music:/data/music
    ports:
      - 8096:8096
      - 7359:7359/udp # Discovery
      - 1900:1900/udp # DLNA
    restart: unless-stopped
